### ISSUE TITLE
unirecfilter: Allow "PROTOCOL==number" in filter

### ISSUE THREAD

**Issue by vaclavbartos** [CESNET/Nemea-Modules#21]
In filter specification, a value of PROTOCOL field must contain a name of the protocol (UDP, TCP and ICMP as a token, others must be encoled in quotes as a string). Numbers are not allowed ("syntax error" without any meanigful explanation is generated).

A change is needed to allow number as a PROTOCOL value.

It would also be nice to remove the special handling of UDP,TCP,ICMP and treat all protocol names the same.

**Comment by cejkato2** [comment]
It should treat all protocol names according to this line:
https://github.com/CESNET/Nemea-Modules/blob/master/unirecfilter/bison/functions.c#L624

However, we should also allow to specify a number - I agree with this...

I've opened another issue about improvement of docs: #22
