### ISSUE TITLE
Improvement of documentation of unirecfilter

### ISSUE THREAD

**Issue by cejkato2** [CESNET/Nemea-Modules#22]
README of UnirecFilter tells no information about PROTOCOL field.
This should be documented.

In addition, deeper analysis of this module would be helpful. The goal is to improve and complete docs for this module and add examples.

**Comment by vaclavbartos** [comment]
See commits d4d9d8ff and 25db3d67 to see recent changes. Some slightly changed (or rather fixed) the filter language.
