### ISSUE TITLE
Flow records aggregation

### ISSUE THREAD

**Issue by cejkato2** [CESNET/Nemea-Modules#28]
The topic of flow aggregation was opened by @whitetiger21022014 as a PR...
However, it is highly relevant so let's move the discussion here.

The question: https://github.com/CESNET/Nemea-Modules/pull/27#issue-203536150

My response: https://github.com/CESNET/Nemea-Modules/pull/27#issuecomment-275749760

**Comment by whitetiger21022014** [comment]
@cejkato2 
Thank for your time and Top-n module, last question
May I compile **topn, logger** module **in OpenWRT** ?
May I compile **tunnel_detection module** (Nemea-Detectors) **in OpenWRT** ?

**Comment by cejkato2** [comment]
I think it should be possible but it will take some effort... We would be glad for any help so let me explain some principles of compiling NEMEA for OpenWrt.
The basic info should be at http://nemea.liberouter.org/openwrt/:
1. clone OpenWrt 15.05
2. add NEMEA feed using the guide in README: https://github.com/CESNET/Nemea-OpenWRT/
3. select NEMEA packages in `menuconfig` of OpenWrt
4. `make`

That was about compilation of our version.
You will need some modifications so let me show you so internals.
After adding the feed, there are `feeds/nemea/libs/nemea-framework` and `feeds/nemea/utils/nemea-modules/` in your openwrt directory.

To add topn and logger, you will need to change https://github.com/CESNET/Nemea-OpenWRT/blob/master/utils/nemea-modules/Makefile#L12 that defines git revision.
There is also a patch https://github.com/CESNET/Nemea-OpenWRT/blob/master/utils/nemea-modules/patches/001-removemodules.patch that modifies a set of modules to compile.

I think the `topn` module should be easier to add because it has no special dependencies.

In the past, `logger` used openmp but as I'm looking into repo, it is already rewritten so it uses "just" pthread -> it should be fine now.

Please, let us know if you make some progress... Thanks in advance.

**Comment by whitetiger21022014** [comment]
@cejkato2
Thanks you so much
With flow_meter module, it will be great if it supports BPF filter option when capturing live interface

**Comment by cejkato2** [comment]
@havraji6 worked on #29, thank you!

**Comment by whitetiger21022014** [comment]
@cejkato2
I just compile and test with topN module
topn -n 10 -l 120 -i "t:127.0.0.1:11111"

Top flows based on transferred bytes
------------------------------------
N | Src ip | Dst ip | Src port | Dst port | Protocol | Bytes
1       192.168.111.138 192.168.111.1   22      51670   6       19952
2       192.168.111.1   192.168.111.138 51670   22      6       12248
3       192.168.111.138 192.168.111.1   22      52170   6       8176
**4       138.201.184.12  192.168.111.138 80      44700   6       4307
5       138.201.184.12  192.168.111.138 80      44690   6       4307
6       138.201.184.12  192.168.111.138 80      44698   6       4307
7       138.201.184.12  192.168.111.138 80      44702   6       4307**
...................................
Top flows based on transferred packets
....................................
===================================================

There are 4 lines (number 4,5,6,8) with the same dest_port, so **it should aggregate to one line**
I tested with many tools (nfdump, silk-rwfilter) , but it can't support openWRT, so I have idea for enhance topN in the future
- Do not need to show many sections (top flows, top packets, top port,...) , only one section like 
TIME_FIRST| DURATION (or TIME_LAST)| SRC_IP| DST_IP| SRC_PORT| DST_PORT| PROTOCOL| PACKETS| BYTES		(and future: SRC_MAC, DST_MAC field)

and user can write parse_script for extracting the data as they need

topn -l 120 -i "t:127.0.0.1:11111" **-A sIP,dIP,dPort -O bytes -n 10**

-A aggregation: ex: sIP, dIP, dPort, sPort, Protocol
-O order:	ex: bytes | packets
-w outputfile 

=== 2017-02-07 09:10:16
=== Top flows based on topN ......

TIME_FIRST| DURATION (or TIME_LAST)| SRC_IP| DST_IP| SRC_PORT| DST_PORT| PROTOCOL| PACKETS| BYTES		(and future: SRC_MAC, DST_MAC field)
timestamp|	..........				|	192.168.111.138|192.168.111.1|   22222|      22|   6|    33|   1995200000
timestamp| ...........				|	138.201.184.12|	192.168.111.138| 11111|      443|   6|    44|   43070000

Summary: Total rows: 111	......................
