### ISSUE TITLE
Unstable if flow_meter uses with many plugins in one command line

### ISSUE THREAD

**Issue by whitetiger21022014** [CESNET/Nemea-Modules#30]
@cejkato2,
After testing flow_meter, logger many times (all modules installed in Centos 6.3), I have some comments as below

**1. Use many plugins in one command line (eg: basic,http,dns)**
flow_meter -i t:11111,t:11112,t:11113 -p basic,http,dns -I eth1
ex: logger -i t:11113 -t
it is unstable: sometimes I can get flows, sometimes can not

But if I use with many command lines as below
flow_meter -i t:11111 -p basic -I eth1
flow_meter -i t:11112 -p http -I eth1
flow_meter -i t:11113 -p dns -I eth1
ex: logger -i t:11113 -t
it is stable, I can get flows

**2. Can not auto-kill logger if use unix socket process** 
flow_meter -i u:c -p **dns** -I eth1
Then I use flow_meter -i u:c -p **http** -I eth1, with the same socket  u:c
ex: logger -i u:c -t

When changes socket, i think Nemea should also kill or refresh **'names of fields'** logger socket 
I tested with TCP socket. If I kill flow_meter, then Nemea will auto-kill logger

**Comment by havraji6** [comment]
Hello, thanks for the comment.

**1. Use many plugins in one command line (eg: basic,http,dns)**
The default timeout on output interfaces is `WAIT`. This will cause module to stop and wait when trying to send message to output interface with no connected clients. ` flow_meter -i t:11111,t:11112,t:11113 -p basic,http,dns -I eth1` was waiting for clients to connect to `11111` or `11112` port while you expected flows on `11113` port.

However `WAIT` as default timeout is not the best choice for exporter. We will change the default timeout to `HALF_WAIT` to prevent this behavior. You can always set timeout manually.
For more information about timeouts see `logger -h trap` or `flow_meter -h trap`

**2. Can not auto-kill logger if use unix socket process**
I will need more info. What was the output of `logger` when you killed `flow_meter` with TCP socket?

I killed `flow_meter` with TCP socket and `logger` returned an `trap_recv() error` if you mean this by **auto-kill**.

**Comment by whitetiger21022014** [comment]
Hi Havraji6,
- I just tested with timeout=HALF_WAIT, it works so well
- I just reconsider my old idea with auto-kill, with old commits, if used command **pkill -9 meter** and logger also be killed. Today with the same command (pkill -9 meter) and logger is still alive. It is my expected
Thanks you!

**Comment by cejkato2** [comment]
@whitetiger21022014 generally, it should be better to kill NEMEA modules using `SIGINT` - this usually breaks the main loop in modules...

That auto-kill "feature" you mentioned is something caused by "ending message". E.g. when we use `logreplay`, it sends this message by default in order to stop connected modules when the CSV file is read till the end.
However, I wish to get so called "signalling" feature finished - it will improve internal mechanism of e.g. this ending message use-case.

Thank you very much for all feedback and notes you have already provided.
