### ISSUE TITLE
Question: DIR_BIT_FIELD of interface network

### ISSUE THREAD

**Issue by whitetiger21022014** [CESNET/Nemea-Modules#40]
Dear Nemea Team,
I used logger command for show logging from flow_meter and DIR_BIT_FIELD always is 0

May I get the direction value of incoming and outgoing traffic of interface network, like ingress and egress of  netflow v9?
Thanks,

**Comment by havraji6** [comment]
Hello,
`DIR_BIT_FIELD` is not used at the moment since `libpcap` does not provide information about packet direction.

Getting direction of flow is part of future work.

**Comment by whitetiger21022014** [comment]
Thank you
