### ISSUE TITLE
'uint64 BYTES' in openWRT always has zero value

### ISSUE THREAD

**Issue by whitetiger21022014** [CESNET/Nemea-Modules#41]
Dear Nemea team,
I have problem with OpenWRT as below
When I tested with commit: https://github.com/CESNET/Nemea-Modules/commit/e115bd7940b8da4d7dbb8d0d98273ff72ac23e67

Run flow_meter in OpenWRT

- Run logger in OpenWRT, it will show 192.168.11.11,10.10.10.10**,0,**0
**value of 'uint64 BYTES; always zero** 

- But if I use endiverter on Centos and connect to openWRT, then use logger in Centos, the BYTE will have value
192.168.11.11,10.10.10.10,**222**,0
BRs

**Comment by havraji6** [comment]
Hello,
problem should be fixed now.

Thanks for pointing this out.

**Comment by whitetiger21022014** [comment]
Thanks @havraji6,

My comment is just enhanced option 
- logger with -w, can rotate logging, eg. will rotate log file, if it has max (nnn Bytes size) or after nnn minutes
 - Export to IPFIX collector
flow_meter will stop if it can not connect to 'IPFIX collector'. So if we restart server or  'IPFIX collector' has problem, flow_meter should try to connect and **will re-send** when 'IPFIX collectorl' is available

flow_meter -p basic -x **127.0.0.1**:11111 -I eth1
Connecting to IP 127.0.0.1
Cannot connect to collector: **Connection refused**

flow_meter -p basic -x **192.168.2.40:**11111 -I eth1
Connecting to IP 192.168.2.40
**Cannot connect to collector: No route to host**

BRs,
