### ISSUE TITLE
anonymizer: unchecked rv of fgets!

### ISSUE THREAD

**Issue by jaroslavh** [CESNET/Nemea-Modules#74]
Here: https://github.com/CESNET/Nemea-Modules/blob/master/anonymizer/anonymizer.c#L151
Wrong usage of fgets, check if it succeeded.

Also should revisit this old code and check for other possible problems.

**Comment by jaroslavh** [comment]
@cejkato2 Is this module still used? There is multiple problems with the code after watching the Coverity Scan report. Should I try to bring it up to date with our todays' standards?

**Comment by vaclavbartos** [comment]
My opinion: We currently don't use it, but we probably should, so it's likely we will need it again in the future. Also, it may be useful for someone else. And we mention online anonymization in the paper about Nemea. So, in my opinion, this module is quite important and should be ready to use. If there are any severe problems, please, try to fix them.

**Comment by cejkato2** [comment]
Thanks for improvements.
