### ISSUE TITLE
vportscan aggregation logger does not work

### ISSUE THREAD

**Issue by thorgrin** [CESNET/Nemea-Modules#75]
When I try to run vportscan aggregation logger, it fails:

`vportscan_agg_logger_stderr`:
```
Fri Jul 13 16:07:46 2018 [INFO] Supervisor - executed command: /usr/bin/nemea/logger   -t   -T   -a   /data/vportscan/alerts.log   -i   t:12005   (null)
trap_recv() error: output and input interfaces data formats or data specifiers mismatch.
```

I have verified that the port 12005 belongs to the `vportscan_aggregator`. Is there anything else that I can check or do to make it work? Thanks

**Comment by jaroslavh** [comment]
If I understand it right - you used it this way:

vportscan_detector --> vportscan_aggregator --> logger FAIL

Proper usage is:
vportscan_detector --> vportscan_aggregator --> json_dump.py OK

https://github.com/CESNET/Nemea-Detectors/blob/master/vportscan_detector/vportscan_aggregator.py#L121 here vportscan_aggregator is set to JSON format which is not documented anywhere.

If I got it right please notify me @thorgrin and I will update the documentation of vportscan_detector.

**Comment by thorgrin** [comment]
Yes, this is exactly the case. Just updating the docs so that it is clear when the module outputs unirec and when JSON should be enough.

**Comment by jaroslavh** [comment]
Created a [pull-request](https://github.com/CESNET/Nemea-Detectors/pull/35) for this. @thorgrin please review :)
