### ISSUE TITLE
vportscan AggrWin is fixed

### ISSUE THREAD

**Issue by thorgrin** [CESNET/Nemea-Modules#80]
I'm not really sure whether it's a bug or not, but the AggrWin of vportscan2idea reporter is fixed to 10 minutes (https://github.com/CESNET/Nemea-Modules/blob/master/report2idea/vportscan/vportscan2idea.py#L52). But this window can be set by the vportscan aggregator, can't it? Therefore, I think that this value should be based on the aggregator configuration. Can you please explain?

**Comment by thorgrin** [comment]
The same applies to haddrscan.

**Comment by vaclavbartos** [comment]
You're right, it should be possible to set it to match the setting of the corresponding aggregator.

I added a possibility to set it by a command line argument (`--aggrwin`) - because it's the same way as aggregator modules are configured and also there's probably no other reasonable way.
