### ISSUE TITLE
Unirecfilter: Support for "IN" operator for IP prefix

### ISSUE THREAD

**Issue by fkrestan** [CESNET/Nemea-Modules#88]
This issue is for tracking work on new operator "IN" for IP prefix filtering in `unirecfilter` module.

Example usage:
```
.. -F "DST_IP IN 192.168.0.0/24" ...
```

This would filter out all records, with destination IP address not in 192.168.0.0/24.

**Comment by cejkato2** [comment]
Operator `IN` is still not available, however, we have added a feature about filtering by IP prefix.

See #89 .

Is it enough to close this issue? @fkrestan

**Comment by fkrestan** [comment]
Very nice! :) Thanks
